#!/usr/bin/env python

from pathlib import Path
import shutil

import jupytext
import nbconvert


solutions_folder = Path('solutions')
solutions_folder.mkdir(exist_ok=True)

for source in Path('.').glob("*exercises.md"):
    shutil.copy(source, solutions_folder / source.name)
    notebook = jupytext.read(source)
    notebook.cells = [
        cell for cell in notebook.cells
        if (
            cell.cell_type == "markdown"
            or "solution" not in cell.source.lower()
        )
    ]
    jupytext.write(notebook, source)